- name: Create Users
  user: name={{item.key}} state={{item.value.state}} uid={{item.value.uid}} shell={{item.value.shell}} password={{item.value.password}} update_password=on_create
  with_dict: "{{users}}"
  sudo: yes

- name: Test ping
  ping:

#- name: Add SSH Keys
#  authorized_keys: user={{item.key}} key={{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}
#  with_dict: "{{users}}"
#  sudo: yes
